# Generated by Django 4.2.7 on 2024-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(default='1168922384', max_length=150, verbose_name='id в телеграм'),
            preserve_default=False,
        ),
    ]
