# Generated by Django 4.2.7 on 2024-03-14 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('habit_time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=500, verbose_name='Привычка')),
                ('is_nice', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('attached_habit', models.IntegerField(blank=True, null=True, verbose_name='Привязанная привычка')),
                ('period', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность в днях')),
                ('bonus', models.CharField(max_length=500, verbose_name='Вознаграждение')),
                ('lead_time', models.TimeField(verbose_name='Время на  выполнение привычки')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Общий доступ')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
