# Generated by Django 4.2.7 on 2024-03-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='action',
            new_name='habit',
        ),
    ]
