# Generated by Django 4.2.7 on 2024-03-14 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность в днях'),
            preserve_default=False,
        ),
    ]
