# Generated by Django 4.2.7 on 2024-03-15 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='lead_time_new',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на  выполнение привычки в секундах'),
            preserve_default=False,
        ),
    ]
