# Generated by Django 4.2.7 on 2024-03-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habit_lead_time_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='lead_time',
        ),
    ]
