# Generated by Django 4.2.7 on 2024-03-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habit_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='data_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
    ]
