# Generated by Django 4.2.7 on 2024-03-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_habit_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
