# Generated by Django 4.2.7 on 2024-03-24 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habit_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='lead_time_new',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на  выполнение привычки в секундах'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность в днях'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место'),
        ),
    ]
