# Generated by Django 4.2.7 on 2024-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_alter_habit_habit_alter_habit_lead_time_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(default='на диване', max_length=100, verbose_name='Место'),
            preserve_default=False,
        ),
    ]
