# Generated by Django 4.2.7 on 2024-03-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_alter_habit_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_time',
            field=models.TimeField(default='09:00:00', verbose_name='Время'),
        ),
    ]
