# Generated by Django 4.2.7 on 2024-03-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_alter_habit_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit',
            field=models.CharField(default='привычка', max_length=500, verbose_name='Привычка'),
            preserve_default=False,
        ),
    ]
