# Generated by Django 4.2.7 on 2024-03-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0015_alter_habit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='data_create',
            field=models.DateField(auto_now_add=True, default='1999-01-01', verbose_name='дата создания'),
            preserve_default=False,
        ),
    ]
