# Generated by Django 4.2.7 on 2024-03-25 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0016_alter_habit_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='lead_time_new',
            field=models.IntegerField(default='1', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на  выполнение привычки в секундах'),
        ),
    ]
