# Generated by Django 4.2.7 on 2024-03-25 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0018_alter_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='attached_habit_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nice_habit', to='habits.habit', verbose_name='Связанная привычка'),
        ),
    ]
