# Generated by Django 4.2.7 on 2024-03-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0020_alter_habit_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='attached_habit',
        ),
    ]
